### ISSUE TITLE
Note: Hair colors for dyed tips are not the same in-game as root hair colors.

### ISSUE THREAD

**Issue by 8bllgrl** [ktisis-tools/Ktisis#103]
![image](https://user-images.githubusercontent.com/102974548/213947085-228d76c3-b9a0-425d-896b-a1decd465546.png)

Sorry for using Anamnesis as the example, but this is how the colors should appear differently.

Hair roots:
![image](https://user-images.githubusercontent.com/102974548/213947160-0380eb98-c5d1-4646-b7f6-2efab3bd8904.png)
Hair ends:
![image](https://user-images.githubusercontent.com/102974548/213947148-32b583e0-ceb8-468d-be59-f60cc71231fb.png)

![image](https://user-images.githubusercontent.com/102974548/213947160-0380eb98-c5d1-4646-b7f6-2efab3bd8904.png)![image](https://user-images.githubusercontent.com/102974548/213947148-32b583e0-ceb8-468d-be59-f60cc71231fb.png)

**Comment by chirpxiv** [comment]
Fixed by a4443d6
