### ISSUE TITLE
import/export appearance does not import weapon 

### ISSUE THREAD

**Issue by thechocorooms** [ktisis-tools/Ktisis#107]
Hi, I made a quick 'gearset' in ktisis for easy clearing of outfit items, since my game tends to freeze if i just remove everything and then try to redraw my character (something to do with not having a weapon equipped I think) but noticed when I do this via ktisis it does not overwrite my weapon with the one in the set I exported. 

Here is the set I made in ktisis, very simple:
![ffxiv_dx11_sJWxMpmKsT](https://user-images.githubusercontent.com/85652485/226175968-186856e4-e8ca-4715-bce2-ad2ece197a8a.png)

screenshot of the options selected in ktisis for import/export:
![ffxiv_dx11_nUWdzMCFus](https://user-images.githubusercontent.com/85652485/226176028-656cdd6e-6332-48c8-9d8f-2f2feaadf6fb.png)

screenshot of the options selected in ktisis for import/export, and what it imports onto the character - note that The Emperor's New Fists is not there, but the weapon that my character had equipped.
![ffxiv_dx11_RNgI5cBQes](https://user-images.githubusercontent.com/85652485/226176055-5898bd0d-eba0-4dc3-8953-59790a44e6f7.png)

**Comment by chirpxiv** [comment]
Fixed by 13d7d23
