### ISSUE TITLE
weird customize+ issue?

### ISSUE THREAD

**Issue by itporl** [ktisis-tools/Ktisis#108]
hi not sure if its on ktisis side but i been having this problem with customize+ on 
![image_2023-05-12_035845903](https://github.com/ktisis-tools/Ktisis/assets/101921294/c27209d4-8819-4ef5-ac53-4e93c6fcb95d)

**Comment by chirpxiv** [comment]
This is caused by a recent update to Customize+. You can report it on their github repo [here](https://github.com/XIV-Tools/CustomizePlus/issues).
