### ISSUE TITLE
Crash when changing target actor while loading actor gear

### ISSUE THREAD

**Issue by Mastodonot** [ktisis-tools/Ktisis#110]
Hello and thank you for this wonderful plugin!
I'm not sure if Linux in general is "supported", but I'll file a report.

There is a constant crashing upon using Ktisis, by simply using it as intended to pose pictures. Both my main computer and Steam Deck are affected.

_Steps to reproduce:_

1: Log into the game using XIVLauncher.Core.
2: Enter /gpose and load Ktisis.
**3a**: Change the actors' gear (You can trigger the crash quicker by scrolling through the gear list using Up-Arrow or Down-Arrow).
**3b**: Targeting another actor using TAB or LEFT-MOUSE (I can't reproduce this on a consistent basis but it'll trigger eventually mid-pose).
4: The game freezes or outright crashes to desktop.

_What measures I tried:_

- Try different versions of XIVLauncher.Core (Official Flatpak as well as AUR and COPR).
- Try different versions of Linux distros (Arch, OpenSUSE, Fedora).
- Starting from absolute scratch, with fresh Dalamud and installing only Ktisis = Still crashes.

It's worth noting that an older version of Ktisis (0.2.4.2) worked without any issues, it's only after version 0.2.5 the problems started to occur.

This is a huge bummer as Ktisis is the only real means to pose on the Steam Deck and Linux Desktop without resorting to dual-booting or Winetricks.

Also, this is my first bug-report of this kind so please bear with me.
Thank you!

**Comment by chirpxiv** [comment]
Have been able to reproduce this on Windows, but the nature of this crash is going to be hard to debug - will try implementing some guard rails to see if that fixes anything. Thanks!

**Comment by Mastodonot** [comment]
So I may have an update to this, today I was able to reproduce the crash without doing Step **3a**.

When I pose I sometimes use +3 actors, and to change between actors I tend press TAB alot.
Every time I press TAB or open the "Change Equipment"-window, Ktisis "hitches" for a split second -- might be related?

Dalamud managed to log the moment it crashed, I'll attach it for you.

[dalamud.log](https://github.com/ktisis-tools/Ktisis/files/11680876/dalamud.log)

**Comment by chirpxiv** [comment]
Sorry for the delay, latest release should address this - let me know if it's resolved for you!

**Comment by Mastodonot** [comment]
So I got the chance to try this for the last few days...
I'm happy to report that I can't reproduce this anymore, not even when intentionally trying to break it.

The latest version definitely solved the crashes, so I'll be closing this as resolved.

Thank you so much for the work you do!
