### ISSUE TITLE
game exit crash

### ISSUE THREAD

**Issue by MaxineMutini** [ktisis-tools/Ktisis#70]
got a crash while exiting, heres the log
[dalamud_appcrash_20221208_142245_979_3436.log](https://github.com/ktisis-tools/Ktisis/files/10188832/dalamud_appcrash_20221208_142245_979_3436.log)
edit: its worth noting that i did nothing with the plugin except explore the settings menu. this is not a game breaking bug, yall are doing great, the ingame angle draw lines and editing alone is amazing work

**Comment by Maxunit** [comment]
Thank you for the log.

Crashes when exiting the game can have many reasons. Are you using any other Plugins like Penumbra?

**Comment by sprocketaudio** [comment]
the log looks related to Ktisis @chirpxiv

**Comment by MaxineMutini** [comment]
im not using penumbra

**Comment by chirpxiv** [comment]
The log shows that this is caused by Ktisis's Actor editing window. Something to do with ImGui, not immediately clear what - will look into this when I'm free.

**Comment by chirpxiv** [comment]
Pushed commit #64b907a aiming to fix this, will work on getting another release out.

**Comment by chirpxiv** [comment]
Last night's update included a patch that aimed to fix this - are you able to confirm?
